import React from 'react';
import { FileText, Eye, Download, Zap, Trash2 } from 'lucide-react';
import { useQuery } from 'react-query';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import LoadingSpinner from '../components/UI/LoadingSpinner';
import { toast } from 'react-toastify';

const ReportsPage = () => {
  const navigate = useNavigate();
  const { data: reportsData, isLoading, error, refetch } = useQuery(
    ['reports'],
    async () => {
      const response = await axios.get('/api/reports?limit=50');
      return response.data;
    },
    {
      refetchInterval: 5000 // Refresh every 5 seconds to show status updates
    }
  );

  const handleViewReport = (reportId) => {
    navigate(`/reports/${reportId}`);
  };

  const handleDeleteReport = async (reportId) => {
    if (!window.confirm('Are you sure you want to delete this report? This action cannot be undone.')) {
      return;
    }

    try {
      const res = await axios.delete(`/api/reports/${reportId}`);
      toast.success(res.data.message);
      refetch();
    } catch (err) {
      console.error('Delete failed', err);
      toast.error(err.response?.data?.message || 'Failed to delete report');
    }
  };

  const handleDownloadReport = async (reportId, format = 'pdf') => {
    try {
      const endpoint = format === 'pdf' ? `/api/reports/${reportId}/download` : `/api/reports/${reportId}/export/docx`;
      const response = await axios.get(endpoint, {
        responseType: 'blob'
      });
      
      const file = new Blob([response.data], { type: response.headers['content-type'] });
      const fileURL = URL.createObjectURL(file);
      const link = document.createElement('a');
      link.href = fileURL;
      
      const contentDisposition = response.headers['content-disposition'];
      let fileName = `report-${reportId}.${format}`;
      if (contentDisposition) {
        const fileNameMatch = contentDisposition.match(/filename="(.+)"/);
        if (fileNameMatch && fileNameMatch.length === 2) {
          fileName = fileNameMatch[1];
        }
      }
      
      link.setAttribute('download', fileName);
      document.body.appendChild(link);
      link.click();
      link.remove();
      toast.success(`Report downloaded as ${format.toUpperCase()}`);
    } catch (err) {
      console.error('Error downloading report:', err);
      toast.error('Failed to download report. Please check if the report is ready.');
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <LoadingSpinner size="large" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="text-center py-12">
        <p className="text-red-400">Error loading reports: {error.message}</p>
        <button
          onClick={() => refetch()}
          className="btn-primary mt-4"
        >
          Retry
        </button>
      </div>
    );
  }

  const reports = reportsData?.reports || [];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-dark-100">Reports</h1>
          <p className="text-dark-300 mt-2">Generate and manage forensic reports</p>
        </div>
        <button
          onClick={() => navigate('/cases')}
          className="btn-primary"
        >
          <Zap className="h-4 w-4 mr-2" />
          Generate New Report
        </button>
      </div>

      {reports.length > 0 ? (
        <div className="card">
          <div className="card-body">
            <div className="table-container">
              <table className="table">
                <thead className="table-header">
                  <tr>
                    <th>Report ID</th>
                    <th>Title</th>
                    <th>Case</th>
                    <th>Status</th>
                    <th>Generated By</th>
                    <th>Created</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody className="table-body">
                  {reports.map((report) => {
                    const statusColors = {
                      draft: 'bg-gray-100 text-gray-800',
                      processing: 'bg-orange-100 text-orange-800',
                      completed: 'bg-blue-100 text-blue-800',
                      finalized: 'bg-green-100 text-green-800'
                    };

                    return (
                      <tr key={report._id}>
                        <td>
                          <span className="font-mono text-sm text-dark-300">
                            {report.reportId || report._id.substring(0, 8)}
                          </span>
                        </td>
                        <td>
                          <p className="font-medium text-dark-100">{report.title}</p>
                        </td>
                        <td>
                          <span className="text-sm text-dark-300">
                            {report.caseId?.caseId || 'N/A'}
                          </span>
                        </td>
                        <td>
                          <span className={`status-badge ${statusColors[report.status] || statusColors.draft}`}>
                            {report.status}
                          </span>
                        </td>
                        <td>
                          <span className="text-sm text-dark-300">
                            {report.generatedBy?.firstName} {report.generatedBy?.lastName}
                          </span>
                        </td>
                        <td>
                          <span className="text-sm text-dark-300">
                            {new Date(report.createdAt).toLocaleDateString()}
                          </span>
                        </td>
                        <td>
                          <div className="flex space-x-2">
                             <button
                              className="text-primary-400 hover:text-primary-300"
                              onClick={() => handleViewReport(report._id)}
                              title="View Report"
                            >
                              <Eye className="h-4 w-4" />
                            </button>
                            {report.status !== 'finalized' && (
                              <button
                                className="text-red-400 hover:text-red-300"
                                onClick={() => handleDeleteReport(report._id)}
                                title="Delete Report"
                              >
                                <Trash2 className="h-4 w-4" />
                              </button>
                            )}
                            {report.status === 'completed' || report.status === 'finalized' ? (
                              <div className="flex space-x-1">
                                <button
                                  className="text-primary-400 hover:text-primary-300 p-1 rounded hover:bg-primary-500/10"
                                  onClick={() => handleDownloadReport(report._id, 'pdf')}
                                  title="Download PDF"
                                >
                                  <Download className="h-4 w-4" />
                                </button>
                                <button
                                  className="text-primary-400 hover:text-primary-300 p-1 rounded hover:bg-primary-500/10"
                                  onClick={() => handleDownloadReport(report._id, 'docx')}
                                  title="Download DOCX"
                                >
                                  <FileText className="h-4 w-4" />
                                </button>
                              </div>
                            ) : null}
                          </div>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      ) : (
        <div className="card">
          <div className="card-body text-center py-12">
            <FileText className="h-16 w-16 text-dark-500 mx-auto mb-4" />
            <h3 className="text-xl font-medium text-dark-100 mb-2">No reports generated yet</h3>
            <p className="text-dark-400 mb-6">Start by selecting a case to generate your first forensic report</p>
            <button
              onClick={() => navigate('/cases')}
              className="btn-primary inline-flex items-center"
            >
              <Zap className="h-4 w-4 mr-2" />
              Generate First Report
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default ReportsPage;